# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
e1 = Enterprise.create(name: 'Softtek')
e2 = Enterprise.create(name: 'Walmart')
e3 = Enterprise.create(name: 'Vips')
e4 = Enterprise.create(name: 'EPura')
e5 = Enterprise.create(name: 'Hitss')
e6 = Enterprise.create(name: 'Hildebrando')
e7 = Enterprise.create(name: 'Salinas')
e8 = Enterprise.create(name: 'Inbursa')
e9 = Enterprise.create(name: 'Carso')
e10 = Enterprise.create(name: 'Samborns')
e11 = Enterprise.create(name: 'American Eagle')





Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e2)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e2)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e2)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e2)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e2)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e3)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e3)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e3)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e4)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e5)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e6)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e7)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e1)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e8)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e9)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e8)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e9)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 5, enterprise:e8)
Reclamo.create(comentario:'No cumplen', user_id: 6, enterprise:e9)
Reclamo.create(comentario:'No cumplen', user_id: 7, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 1, enterprise:e10)
Reclamo.create(comentario:'No cumplen', user_id: 2, enterprise:e8)
Reclamo.create(comentario:'No cumplen', user_id: 3, enterprise:e9)
Reclamo.create(comentario:'No cumplen', user_id: 4, enterprise:e10)
